"""empty message

Revision ID: d6f0990c4898
Revises: e392893c1958
Create Date: 2021-01-17 16:02:54.920955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f0990c4898'
down_revision = 'e392893c1958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
